import type { Express } from "express";

import route1 from "./routes/agent";
import route2 from "./routes/agent/accept";
import route3 from "./routes/agent/accept/get";
import route4 from "./routes/agent/answer";
import route5 from "./routes/agent/authorize/grant";
import route6 from "./routes/agent/authorize/list";
import route7 from "./routes/agent/canvasResult";
import route8 from "./routes/agent/create";
import route9 from "./routes/agent/events/get";
import route10 from "./routes/agent/get";
import route11 from "./routes/agent/list";
import route12 from "./routes/agent/mentionSource";
import route13 from "./routes/agent/message";
import route14 from "./routes/agent/rename";
import route15 from "./routes/agent/run/control";
import route16 from "./routes/agent/run/get";
import route17 from "./routes/agent/run/list";
import route18 from "./routes/agent/run/review";
import route19 from "./routes/agent/skills";
import route20 from "./routes/agents/a2a/get";
import route21 from "./routes/agents/a2a/save";
import route22 from "./routes/agents/connect";
import route23 from "./routes/agents/get";
import route24 from "./routes/agents/install";
import route25 from "./routes/agents/read";
import route26 from "./routes/agents/save";
import route27 from "./routes/agents/setEnabled";
import route28 from "./routes/agents/uninstall";
import route29 from "./routes/ai/explain";
import route30 from "./routes/ai/generate";
import route31 from "./routes/ai/media/generate";
import route32 from "./routes/ai/media/getJob";
import route33 from "./routes/ai/media/list";
import route34 from "./routes/ai/media/models";
import route35 from "./routes/ai/media/retryCollection";
import route36 from "./routes/ai/models";
import route37 from "./routes/assets/list";
import route38 from "./routes/assets/mkdir";
import route39 from "./routes/assets/read";
import route40 from "./routes/assets/remove";
import route41 from "./routes/assets/rename";
import route42 from "./routes/assets/save";
import route43 from "./routes/desktop/clipboard/read";
import route44 from "./routes/desktop/clipboard/write";
import route45 from "./routes/desktop/devtools";
import route46 from "./routes/desktop/openUrl";
import route47 from "./routes/desktop/plugins/install";
import route48 from "./routes/desktop/providerFile/read";
import route49 from "./routes/desktop/providerFile/select";
import route50 from "./routes/desktop/ready";
import route51 from "./routes/desktop/saveFile";
import route52 from "./routes/desktop/selectDirectory";
import route53 from "./routes/desktop/selectSaveFile";
import route54 from "./routes/desktop/update/apply";
import route55 from "./routes/desktop/update/check";
import route56 from "./routes/desktop/update/download";
import route57 from "./routes/desktop/update/index";
import route58 from "./routes/ffmpeg/cancel";
import route59 from "./routes/ffmpeg/download";
import route60 from "./routes/ffmpeg/events";
import route61 from "./routes/ffmpeg/execute";
import route62 from "./routes/ffmpeg/progress";
import route63 from "./routes/ffmpeg/status";
import route64 from "./routes/jobs/cancel";
import route65 from "./routes/jobs/events";
import route66 from "./routes/jobs/get";
import route67 from "./routes/jobs/list";
import route68 from "./routes/jobs/resume";
import route69 from "./routes/mcp/control/events";
import route70 from "./routes/mcp/control/result";
import route71 from "./routes/mcp/control/state";
import route72 from "./routes/mcp/skill";
import route73 from "./routes/mcp/status";
import route74 from "./routes/nodes/files";
import route75 from "./routes/nodes/get";
import route76 from "./routes/nodes/install";
import route77 from "./routes/nodes/save";
import route78 from "./routes/nodes/setEnabled";
import route79 from "./routes/nodes/uninstall";
import route80 from "./routes/plugins/export";
import route81 from "./routes/providers/debug/inspect";
import route82 from "./routes/providers/debug/run";
import route83 from "./routes/providers/media/add";
import route84 from "./routes/providers/media/delete";
import route85 from "./routes/providers/media/list";
import route86 from "./routes/providers/media/models";
import route87 from "./routes/providers/media/save";
import route88 from "./routes/providers/models";
import route89 from "./routes/settings/get";
import route90 from "./routes/settings/personalization/get";
import route91 from "./routes/settings/personalization/save";
import route92 from "./routes/settings/save";
import route93 from "./routes/settings/systemPrompt";
import route94 from "./routes/skills/create";
import route95 from "./routes/skills/get";
import route96 from "./routes/skills/install";
import route97 from "./routes/skills/list";
import route98 from "./routes/skills/move";
import route99 from "./routes/skills/order";
import route100 from "./routes/skills/read";
import route101 from "./routes/skills/save";
import route102 from "./routes/skills/uninstall";
import route103 from "./routes/tools/client";
import route104 from "./routes/tools/get";
import route105 from "./routes/tools/install";
import route106 from "./routes/tools/renderers";
import route107 from "./routes/tools/save";
import route108 from "./routes/tools/setEnabled";
import route109 from "./routes/tools/uninstall";
import route110 from "./routes/workspaces/canvas/command";
import route111 from "./routes/workspaces/canvas/command/get";
import route112 from "./routes/workspaces/canvas/content";
import route113 from "./routes/workspaces/canvas/content/write";
import route114 from "./routes/workspaces/canvas/events";
import route115 from "./routes/workspaces/canvas/get";
import route116 from "./routes/workspaces/canvas/modify";
import route117 from "./routes/workspaces/canvas/remove";
import route118 from "./routes/workspaces/canvas/rename";
import route119 from "./routes/workspaces/check";
import route120 from "./routes/workspaces/files/list";
import route121 from "./routes/workspaces/files/mkdir";
import route122 from "./routes/workspaces/files/read";
import route123 from "./routes/workspaces/files/remove";
import route124 from "./routes/workspaces/files/rename";
import route125 from "./routes/workspaces/files/write";
import route126 from "./routes/workspaces/list";
import route127 from "./routes/workspaces/projects/importLocal";
import route128 from "./routes/workspaces/projects/list";
import route129 from "./routes/workspaces/projects/open";
import route130 from "./routes/workspaces/projects/remove";
import route131 from "./routes/workspaces/projects/rename";

export default (app: Express) => {
  app.use("/api/agent", route1);
  app.use("/api/agent/accept", route2);
  app.use("/api/agent/accept/get", route3);
  app.use("/api/agent/answer", route4);
  app.use("/api/agent/authorize/grant", route5);
  app.use("/api/agent/authorize/list", route6);
  app.use("/api/agent/canvasResult", route7);
  app.use("/api/agent/create", route8);
  app.use("/api/agent/events/get", route9);
  app.use("/api/agent/get", route10);
  app.use("/api/agent/list", route11);
  app.use("/api/agent/mentionSource", route12);
  app.use("/api/agent/message", route13);
  app.use("/api/agent/rename", route14);
  app.use("/api/agent/run/control", route15);
  app.use("/api/agent/run/get", route16);
  app.use("/api/agent/run/list", route17);
  app.use("/api/agent/run/review", route18);
  app.use("/api/agent/skills", route19);
  app.use("/api/agents/a2a/get", route20);
  app.use("/api/agents/a2a/save", route21);
  app.use("/api/agents/connect", route22);
  app.use("/api/agents/get", route23);
  app.use("/api/agents/install", route24);
  app.use("/api/agents/read", route25);
  app.use("/api/agents/save", route26);
  app.use("/api/agents/setEnabled", route27);
  app.use("/api/agents/uninstall", route28);
  app.use("/api/ai/explain", route29);
  app.use("/api/ai/generate", route30);
  app.use("/api/ai/media/generate", route31);
  app.use("/api/ai/media/getJob", route32);
  app.use("/api/ai/media/list", route33);
  app.use("/api/ai/media/models", route34);
  app.use("/api/ai/media/retryCollection", route35);
  app.use("/api/ai/models", route36);
  app.use("/api/assets/list", route37);
  app.use("/api/assets/mkdir", route38);
  app.use("/api/assets/read", route39);
  app.use("/api/assets/remove", route40);
  app.use("/api/assets/rename", route41);
  app.use("/api/assets/save", route42);
  app.use("/api/desktop/clipboard/read", route43);
  app.use("/api/desktop/clipboard/write", route44);
  app.use("/api/desktop/devtools", route45);
  app.use("/api/desktop/openUrl", route46);
  app.use("/api/desktop/plugins/install", route47);
  app.use("/api/desktop/providerFile/read", route48);
  app.use("/api/desktop/providerFile/select", route49);
  app.use("/api/desktop/ready", route50);
  app.use("/api/desktop/saveFile", route51);
  app.use("/api/desktop/selectDirectory", route52);
  app.use("/api/desktop/selectSaveFile", route53);
  app.use("/api/desktop/update/apply", route54);
  app.use("/api/desktop/update/check", route55);
  app.use("/api/desktop/update/download", route56);
  app.use("/api/desktop/update", route57);
  app.use("/api/ffmpeg/cancel", route58);
  app.use("/api/ffmpeg/download", route59);
  app.use("/api/ffmpeg/events", route60);
  app.use("/api/ffmpeg/execute", route61);
  app.use("/api/ffmpeg/progress", route62);
  app.use("/api/ffmpeg/status", route63);
  app.use("/api/jobs/cancel", route64);
  app.use("/api/jobs/events", route65);
  app.use("/api/jobs/get", route66);
  app.use("/api/jobs/list", route67);
  app.use("/api/jobs/resume", route68);
  app.use("/api/mcp/control/events", route69);
  app.use("/api/mcp/control/result", route70);
  app.use("/api/mcp/control/state", route71);
  app.use("/api/mcp/skill", route72);
  app.use("/api/mcp/status", route73);
  app.use("/api/nodes/files", route74);
  app.use("/api/nodes/get", route75);
  app.use("/api/nodes/install", route76);
  app.use("/api/nodes/save", route77);
  app.use("/api/nodes/setEnabled", route78);
  app.use("/api/nodes/uninstall", route79);
  app.use("/api/plugins/export", route80);
  app.use("/api/providers/debug/inspect", route81);
  app.use("/api/providers/debug/run", route82);
  app.use("/api/providers/media/add", route83);
  app.use("/api/providers/media/delete", route84);
  app.use("/api/providers/media/list", route85);
  app.use("/api/providers/media/models", route86);
  app.use("/api/providers/media/save", route87);
  app.use("/api/providers/models", route88);
  app.use("/api/settings/get", route89);
  app.use("/api/settings/personalization/get", route90);
  app.use("/api/settings/personalization/save", route91);
  app.use("/api/settings/save", route92);
  app.use("/api/settings/systemPrompt", route93);
  app.use("/api/skills/create", route94);
  app.use("/api/skills/get", route95);
  app.use("/api/skills/install", route96);
  app.use("/api/skills/list", route97);
  app.use("/api/skills/move", route98);
  app.use("/api/skills/order", route99);
  app.use("/api/skills/read", route100);
  app.use("/api/skills/save", route101);
  app.use("/api/skills/uninstall", route102);
  app.use("/api/tools/client", route103);
  app.use("/api/tools/get", route104);
  app.use("/api/tools/install", route105);
  app.use("/api/tools/renderers", route106);
  app.use("/api/tools/save", route107);
  app.use("/api/tools/setEnabled", route108);
  app.use("/api/tools/uninstall", route109);
  app.use("/api/workspaces/canvas/command", route110);
  app.use("/api/workspaces/canvas/command/get", route111);
  app.use("/api/workspaces/canvas/content", route112);
  app.use("/api/workspaces/canvas/content/write", route113);
  app.use("/api/workspaces/canvas/events", route114);
  app.use("/api/workspaces/canvas/get", route115);
  app.use("/api/workspaces/canvas/modify", route116);
  app.use("/api/workspaces/canvas/remove", route117);
  app.use("/api/workspaces/canvas/rename", route118);
  app.use("/api/workspaces/check", route119);
  app.use("/api/workspaces/files/list", route120);
  app.use("/api/workspaces/files/mkdir", route121);
  app.use("/api/workspaces/files/read", route122);
  app.use("/api/workspaces/files/remove", route123);
  app.use("/api/workspaces/files/rename", route124);
  app.use("/api/workspaces/files/write", route125);
  app.use("/api/workspaces/list", route126);
  app.use("/api/workspaces/projects/importLocal", route127);
  app.use("/api/workspaces/projects/list", route128);
  app.use("/api/workspaces/projects/open", route129);
  app.use("/api/workspaces/projects/remove", route130);
  app.use("/api/workspaces/projects/rename", route131);
}
