import type { Express } from "express";

import route1 from "./routes/agent";
import route2 from "./routes/agent/answer";
import route3 from "./routes/agent/authorize/grant";
import route4 from "./routes/agent/authorize/list";
import route5 from "./routes/agent/canvasResult";
import route6 from "./routes/agent/create";
import route7 from "./routes/agent/events/get";
import route8 from "./routes/agent/get";
import route9 from "./routes/agent/list";
import route10 from "./routes/agent/message";
import route11 from "./routes/agent/rename";
import route12 from "./routes/agent/run/control";
import route13 from "./routes/agent/run/get";
import route14 from "./routes/agent/run/list";
import route15 from "./routes/agent/run/review";
import route16 from "./routes/agent/skills";
import route17 from "./routes/agents/a2a/get";
import route18 from "./routes/agents/a2a/save";
import route19 from "./routes/agents/connect";
import route20 from "./routes/agents/get";
import route21 from "./routes/agents/install";
import route22 from "./routes/agents/read";
import route23 from "./routes/agents/save";
import route24 from "./routes/agents/setEnabled";
import route25 from "./routes/agents/uninstall";
import route26 from "./routes/ai/generate";
import route27 from "./routes/ai/media/generate";
import route28 from "./routes/ai/media/getJob";
import route29 from "./routes/ai/media/list";
import route30 from "./routes/ai/media/models";
import route31 from "./routes/ai/media/retryCollection";
import route32 from "./routes/ai/models";
import route33 from "./routes/assets/list";
import route34 from "./routes/assets/mkdir";
import route35 from "./routes/assets/read";
import route36 from "./routes/assets/remove";
import route37 from "./routes/assets/rename";
import route38 from "./routes/assets/save";
import route39 from "./routes/desktop/clipboard/read";
import route40 from "./routes/desktop/clipboard/write";
import route41 from "./routes/desktop/devtools";
import route42 from "./routes/desktop/openUrl";
import route43 from "./routes/desktop/plugins/install";
import route44 from "./routes/desktop/providerFile/read";
import route45 from "./routes/desktop/providerFile/select";
import route46 from "./routes/desktop/ready";
import route47 from "./routes/desktop/saveFile";
import route48 from "./routes/desktop/selectDirectory";
import route49 from "./routes/desktop/selectSaveFile";
import route50 from "./routes/desktop/update/apply";
import route51 from "./routes/desktop/update/check";
import route52 from "./routes/desktop/update/download";
import route53 from "./routes/desktop/update/index";
import route54 from "./routes/ffmpeg/cancel";
import route55 from "./routes/ffmpeg/download";
import route56 from "./routes/ffmpeg/events";
import route57 from "./routes/ffmpeg/execute";
import route58 from "./routes/ffmpeg/progress";
import route59 from "./routes/ffmpeg/status";
import route60 from "./routes/mcp/control/events";
import route61 from "./routes/mcp/control/result";
import route62 from "./routes/mcp/control/state";
import route63 from "./routes/mcp/skill";
import route64 from "./routes/mcp/status";
import route65 from "./routes/nodes/files";
import route66 from "./routes/nodes/get";
import route67 from "./routes/nodes/install";
import route68 from "./routes/nodes/save";
import route69 from "./routes/nodes/setEnabled";
import route70 from "./routes/nodes/uninstall";
import route71 from "./routes/plugins/export";
import route72 from "./routes/providers/debug/inspect";
import route73 from "./routes/providers/debug/run";
import route74 from "./routes/providers/media/add";
import route75 from "./routes/providers/media/delete";
import route76 from "./routes/providers/media/list";
import route77 from "./routes/providers/media/models";
import route78 from "./routes/providers/media/save";
import route79 from "./routes/providers/models";
import route80 from "./routes/settings/get";
import route81 from "./routes/settings/personalization/get";
import route82 from "./routes/settings/personalization/save";
import route83 from "./routes/settings/save";
import route84 from "./routes/settings/systemPrompt";
import route85 from "./routes/skills/create";
import route86 from "./routes/skills/get";
import route87 from "./routes/skills/install";
import route88 from "./routes/skills/list";
import route89 from "./routes/skills/move";
import route90 from "./routes/skills/order";
import route91 from "./routes/skills/read";
import route92 from "./routes/skills/save";
import route93 from "./routes/skills/uninstall";
import route94 from "./routes/tools/client";
import route95 from "./routes/tools/get";
import route96 from "./routes/tools/install";
import route97 from "./routes/tools/renderers";
import route98 from "./routes/tools/save";
import route99 from "./routes/tools/setEnabled";
import route100 from "./routes/tools/uninstall";
import route101 from "./routes/workspaces/canvas/get";
import route102 from "./routes/workspaces/canvas/modify";
import route103 from "./routes/workspaces/canvas/remove";
import route104 from "./routes/workspaces/canvas/rename";
import route105 from "./routes/workspaces/check";
import route106 from "./routes/workspaces/files/list";
import route107 from "./routes/workspaces/files/mkdir";
import route108 from "./routes/workspaces/files/read";
import route109 from "./routes/workspaces/files/remove";
import route110 from "./routes/workspaces/files/rename";
import route111 from "./routes/workspaces/files/write";
import route112 from "./routes/workspaces/list";
import route113 from "./routes/workspaces/projects/importLocal";
import route114 from "./routes/workspaces/projects/list";
import route115 from "./routes/workspaces/projects/open";
import route116 from "./routes/workspaces/projects/remove";
import route117 from "./routes/workspaces/projects/rename";

export default (app: Express) => {
  app.use("/api/agent", route1);
  app.use("/api/agent/answer", route2);
  app.use("/api/agent/authorize/grant", route3);
  app.use("/api/agent/authorize/list", route4);
  app.use("/api/agent/canvasResult", route5);
  app.use("/api/agent/create", route6);
  app.use("/api/agent/events/get", route7);
  app.use("/api/agent/get", route8);
  app.use("/api/agent/list", route9);
  app.use("/api/agent/message", route10);
  app.use("/api/agent/rename", route11);
  app.use("/api/agent/run/control", route12);
  app.use("/api/agent/run/get", route13);
  app.use("/api/agent/run/list", route14);
  app.use("/api/agent/run/review", route15);
  app.use("/api/agent/skills", route16);
  app.use("/api/agents/a2a/get", route17);
  app.use("/api/agents/a2a/save", route18);
  app.use("/api/agents/connect", route19);
  app.use("/api/agents/get", route20);
  app.use("/api/agents/install", route21);
  app.use("/api/agents/read", route22);
  app.use("/api/agents/save", route23);
  app.use("/api/agents/setEnabled", route24);
  app.use("/api/agents/uninstall", route25);
  app.use("/api/ai/generate", route26);
  app.use("/api/ai/media/generate", route27);
  app.use("/api/ai/media/getJob", route28);
  app.use("/api/ai/media/list", route29);
  app.use("/api/ai/media/models", route30);
  app.use("/api/ai/media/retryCollection", route31);
  app.use("/api/ai/models", route32);
  app.use("/api/assets/list", route33);
  app.use("/api/assets/mkdir", route34);
  app.use("/api/assets/read", route35);
  app.use("/api/assets/remove", route36);
  app.use("/api/assets/rename", route37);
  app.use("/api/assets/save", route38);
  app.use("/api/desktop/clipboard/read", route39);
  app.use("/api/desktop/clipboard/write", route40);
  app.use("/api/desktop/devtools", route41);
  app.use("/api/desktop/openUrl", route42);
  app.use("/api/desktop/plugins/install", route43);
  app.use("/api/desktop/providerFile/read", route44);
  app.use("/api/desktop/providerFile/select", route45);
  app.use("/api/desktop/ready", route46);
  app.use("/api/desktop/saveFile", route47);
  app.use("/api/desktop/selectDirectory", route48);
  app.use("/api/desktop/selectSaveFile", route49);
  app.use("/api/desktop/update/apply", route50);
  app.use("/api/desktop/update/check", route51);
  app.use("/api/desktop/update/download", route52);
  app.use("/api/desktop/update", route53);
  app.use("/api/ffmpeg/cancel", route54);
  app.use("/api/ffmpeg/download", route55);
  app.use("/api/ffmpeg/events", route56);
  app.use("/api/ffmpeg/execute", route57);
  app.use("/api/ffmpeg/progress", route58);
  app.use("/api/ffmpeg/status", route59);
  app.use("/api/mcp/control/events", route60);
  app.use("/api/mcp/control/result", route61);
  app.use("/api/mcp/control/state", route62);
  app.use("/api/mcp/skill", route63);
  app.use("/api/mcp/status", route64);
  app.use("/api/nodes/files", route65);
  app.use("/api/nodes/get", route66);
  app.use("/api/nodes/install", route67);
  app.use("/api/nodes/save", route68);
  app.use("/api/nodes/setEnabled", route69);
  app.use("/api/nodes/uninstall", route70);
  app.use("/api/plugins/export", route71);
  app.use("/api/providers/debug/inspect", route72);
  app.use("/api/providers/debug/run", route73);
  app.use("/api/providers/media/add", route74);
  app.use("/api/providers/media/delete", route75);
  app.use("/api/providers/media/list", route76);
  app.use("/api/providers/media/models", route77);
  app.use("/api/providers/media/save", route78);
  app.use("/api/providers/models", route79);
  app.use("/api/settings/get", route80);
  app.use("/api/settings/personalization/get", route81);
  app.use("/api/settings/personalization/save", route82);
  app.use("/api/settings/save", route83);
  app.use("/api/settings/systemPrompt", route84);
  app.use("/api/skills/create", route85);
  app.use("/api/skills/get", route86);
  app.use("/api/skills/install", route87);
  app.use("/api/skills/list", route88);
  app.use("/api/skills/move", route89);
  app.use("/api/skills/order", route90);
  app.use("/api/skills/read", route91);
  app.use("/api/skills/save", route92);
  app.use("/api/skills/uninstall", route93);
  app.use("/api/tools/client", route94);
  app.use("/api/tools/get", route95);
  app.use("/api/tools/install", route96);
  app.use("/api/tools/renderers", route97);
  app.use("/api/tools/save", route98);
  app.use("/api/tools/setEnabled", route99);
  app.use("/api/tools/uninstall", route100);
  app.use("/api/workspaces/canvas/get", route101);
  app.use("/api/workspaces/canvas/modify", route102);
  app.use("/api/workspaces/canvas/remove", route103);
  app.use("/api/workspaces/canvas/rename", route104);
  app.use("/api/workspaces/check", route105);
  app.use("/api/workspaces/files/list", route106);
  app.use("/api/workspaces/files/mkdir", route107);
  app.use("/api/workspaces/files/read", route108);
  app.use("/api/workspaces/files/remove", route109);
  app.use("/api/workspaces/files/rename", route110);
  app.use("/api/workspaces/files/write", route111);
  app.use("/api/workspaces/list", route112);
  app.use("/api/workspaces/projects/importLocal", route113);
  app.use("/api/workspaces/projects/list", route114);
  app.use("/api/workspaces/projects/open", route115);
  app.use("/api/workspaces/projects/remove", route116);
  app.use("/api/workspaces/projects/rename", route117);
}
